### ISSUE TITLE
Is there a license for this project?

### ISSUE THREAD

**Issue by telharmonium** [kevinvanderlugt/Swift-Walk-Tracker#3]
I discovered this project through this list of **[Open-Source iOS Apps](https://github.com/dkhamsing/open-source-ios-apps/blob/master/README.md#apple-tv)**. I'm interested in learning from your work and contributing if possible, but I'd be more comfortable if there were an explicit license attached.

Thanks for your time.

**Comment by kevinvanderlugt** [comment]
Hi @telharmonium,

Thanks for letting me know how you found it.  You are free to do anything you want with this project and I just added a LICENSE.md for this project.

Cheers!
-Kevin
